apiVersion: v1
kind: Secret
metadata:
  name: saleor-secret
  namespace: saleor
type: Opaque
data:
  SECRET_KEY: dGVzdC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LTEyMzQ1Njc4OTA=  # base64 encoded test key
  DATABASE_URL: cG9zdGdyZXM6Ly9zYWxlb3I6c2FsZW9yQHBvc3RncmVzOjU0MzIvc2FsZW9y  # base64 encoded "postgres://saleor:saleor@postgres:5432/saleor"
  postgres_db: c2FsZW9y  # base64 encoded "saleor"
  postgres_user: c2FsZW9y  # base64 encoded "saleor"
  postgres_password: c2FsZW9y  # base64 encoded "saleor"
