apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor
  namespace: saleor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saleor
  template:
    metadata:
      labels:
        app: saleor
    spec:
      initContainers:
      - name: migrate
        image: matthewntsiful/saleor-webapp:latest
        command: ['sh', '-c', 'echo "Waiting for PostgreSQL..."; until python -c "import psycopg; psycopg.connect(\"host=postgres port=5432 dbname=saleor user=saleor password=saleor\").close()"; do echo "PostgreSQL not ready, waiting..."; sleep 5; done; echo "PostgreSQL ready, running migrations..."; python manage.py migrate --verbosity=2; echo "Migrations completed"']
        envFrom:
        - configMapRef:
            name: saleor-config
        - secretRef:
            name: saleor-secret
      containers:
      - name: saleor
        image: matthewntsiful/saleor-webapp:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        envFrom:
        - configMapRef:
            name: saleor-config
        - secretRef:
            name: saleor-secret
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-service
  namespace: saleor
spec:
  selector:
    app: saleor
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP